[package]
name = "tokio-fcquiche"
version = "0.1.0"
repository = { workspace = true }
license = { workspace = true }
description = "Asynchronous wrapper around the Flexicast extension of quiche"
keywords = ["quic", "flexicast", "tokio"]
categories = { workspace = true }
rust-version = "1.83"
edition = { workspace = true }
readme = "README.md"

[features]
# Forwarded quiche features for re-exports
quiche_internal = ["quiche/internal"]

# Enable tokio tracing
tokio-tracing = ["tokio/tracing"]

# Enable SSLKEYLOGFILE capturing for QUIC connections.
capture_keylogs = []

# Enable qlog support.
qlog = ["quiche/qlog"]

[dependencies]
docopt = "1"
env_logger = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
mio = { workspace = true, features = ["net", "os-poll"] }
nix = { workspace = true, features = ["net", "socket", "uio"] }
octets = { workspace = true }
quiche = { workspace = true }
ring = { workspace = true }
url = { workspace = true }
slab = "0.4"
itertools = "0.15"
clap = { version = "4.1", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full", "tracing"] }
tokio-metrics = { version = "0.4.3" }
console-subscriber = "0.4.1"
chrono = "0.4.41"
socket2 = "0.6.0"

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true, features = ["time", "test-util"] }